import type { NextPage } from 'next'
import Head from 'next/head'
import {
  Card,
  Container,
  Description,
  Footer,
  Logo,
  Main,
  Report,
  Title,
  Works,
} from './indexStyle'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <Title>派遣業務</Title>
      <Description>報告事項を選択して各種報告をしてください。</Description>
      <Main>
        <Works>
          <Card href="https://nextjs.org/docs">勤怠入力</Card>

          <Card href="https://nextjs.org/learn">残業時間報告</Card>

          <Card href="https://github.com/vercel/next.js/tree/master/examples">月次報告</Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            営業報告
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            査定報告
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            周知（役職者）
          </Card>
        </Works>
        <Report>
          <button>入力項目A</button>
          <button>入力項目B</button>
          <button>入力項目C</button>
        </Report>
      </Main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Logo>
            <img src="vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Logo>
        </a>
      </Footer>
    </Container>
  )
}

export default Home
